version: 0.2

phases:
  build:
    commands:
      - echo Build started on $(date)
      - mkdir -p build-output/scripts
      - cp index.html build-output/
      - cp scripts/*.sh build-output/scripts/
      - cp appspec.yml buildspec.yml build-output/
      - cd build-output
      - zip -r ../build-output.zip . -x "*.git/*" 


artifacts:
  files:
    - '**/*'