version: 0.2

phases:
  build:
    commands:
      - echo Build started on date
      
      # Create build-output directory and add files
      - mkdir -p build-output
      - cp index.html build-output/
      - mkdir -p build-output/scripts
      - cp scripts/install_nginx.sh build-output/scripts/
      - cp scripts/start_nginx.sh build-output/scripts/
      - cp appspec.yml build-output/
      - cp buildspec.yml build-output/
      
      # Create the ZIP file with build outputs
      - cd build-output
      - zip -r ../build-output.zip .
      - cd ..
      
      # Find the dynamic deployment path
      - echo "Finding dynamic deployment path..."
      - DEPLOYMENT_PATH=$(find /opt/codedeploy-agent/deployment-root -mindepth 2 -maxdepth 2 -type d -print -exec basename {} \; | head -n 1)
      - DEPLOYMENT_ARCHIVE_PATH="/opt/codedeploy-agent/deployment-root/$DEPLOYMENT_PATH/d-*/deployment-archive"
      - echo "Deployment archive path: $DEPLOYMENT_ARCHIVE_PATH"

      # Create the target directory and extract the ZIP file
      - mkdir -p "$DEPLOYMENT_ARCHIVE_PATH"
      - unzip build-output.zip -d "$DEPLOYMENT_ARCHIVE_PATH"
      
artifacts:
  files:
    - build-output.zip
