version: 0.2

phases:
  build:
    commands:
      - echo Build started on date
      - mkdir -p build-output
      - cp index.html build-output/
      - mkdir -p build-output/scripts
      - cp scripts/install_nginx.sh build-output/scripts/
      - cp scripts/start_nginx.sh build-output/scripts/
      - cp appspec.yml build-output/
      - cp buildspec.yml build-output/
      - cd build-output
      - zip -r ../build-output.zip .

artifacts:
  files:
    - '**/*'