version: 0.2

phases:
  install:
    commands:
      - echo Installing NGINX
      - sudo apt-get update
      - sudo apt-get install nginx -y
  pre_build:
    commands:
      - echo Pre-build started on date
  build:
    commands:
      - echo Build started on date
      - mkdir -p build-output
      - cp index.html build-output/
      - mkdir -p build-output/scripts
      - cp scripts/install_nginx.sh build-output/scripts/
      - cp scripts/start_nginx.sh build-output/scripts/
      - cp appspec.yml build-output/
      - cd build-output
      - zip -r ../build-output.zip .
  post_build:
    commands:
      - echo Build completed

artifacts:
  files:
    - build-output.zip
